import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@styles/main.scss';
import NavBar from '@/components/NavBar';
import 'swiper/css';
import 'swiper/css/pagination';
import Footer from '@/components/Footer';
import SocialLinks from '@/components/Links';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="description"
          content="Welcome to M.ASR Portfolio Stay tuned for all new projects and designs."
        />
        <link rel="icon" type="image/x-icon" href="/me.png" />
        <title>M.ASR Portfolio</title>
      </head>
      <body className={inter.className}>
        <main className=" relative main-background px-2 lg:px-3">
          <NavBar />
          <SocialLinks />
          <section className=" container py-10 min-h-[100dvh]">
            {children}
          </section>
          <Footer />
        </main>
      </body>
    </html>
  );
}
